SELECT *
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
LIMIT 1000;

-- Exercise 1: Count the number of trips in January 2021
SELECT COUNT(vendor_id) AS trip_count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
WHERE EXTRACT(YEAR FROM pickup_datetime) = 2021 
  AND EXTRACT(MONTH FROM pickup_datetime) = 1;

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2021

SELECT SUM(fare_amount) AS total_revenue
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
WHERE EXTRACT(YEAR FROM pickup_datetime) = 2021;

-- Exercise 3: Find the most popular pickup location
SELECT pickup_location_id, COUNT(pickup_location_id) AS trip_count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
GROUP BY pickup_location_id
ORDER BY trip_count DESC
LIMIT 1;


-- Exercise 4: Analyze the number of trips per hour of the day
SELECT 
  EXTRACT(HOUR FROM pickup_datetime) AS hour_of_day, 
  COUNT(vendor_id) AS trip_count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
GROUP BY hour_of_day
ORDER BY hour_of_day;

-- Exercise 5: Calculate the average trip distance
SELECT ROUND(AVG(trip_distance),2) AS average_trip_distance
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`;


-- Exercise 6: Find the longest trip by distance
SELECT trip_distance
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
ORDER BY trip_distance DESC
LIMIT 1;

-- Exercise 7: Calculate the total number of passengers by payment type
SELECT SUM(passenger_count) AS total_passengers,payment_type 
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
GROUP BY payment_type
ORDER BY total_passengers DESC;

-- Exercise 8: Find the most common drop-off location for trips paid by credit card

SELECT 
  dropoff_location_id, 
  COUNT(dropoff_location_id) AS trip_count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
WHERE CAST(payment_type AS STRING) = '1'  -- Compare as string
GROUP BY dropoff_location_id
ORDER BY trip_count DESC
LIMIT 1;



-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT COUNT(vendor_id) AS trip
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
WHERE passenger_count>4;



-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance
SELECT AVG(fare_amount) AS average_fare
FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`
WHERE trip_distance>(
  SELECT AVG(trip_distance)
  FROM `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2021`);
